---
title: ""
subtitle: ""
author: ""
date: ""
toc: true
number-sections: true
format:
  pdf:
    geometry:
      - top=30mm
      - left=20mm
    
---

# Abstract
{A concise summary of the entire paper, often structured according to the IMRaD format}

# Introduction
{What problem was studied? Sets the context, identifies the research gap, and states the research question or hypothesis.}

# Methods
{How was it studied? Provides a detailed description of experimental design, participant selection, data collection, and analysis techniques, allowing for 
replication.}

# Results 
{What were the findings? Presents objective data and findings, often using tables and figures, without interpretation.}

# Discussion
{What do the findings mean? Interprets results, compares them to existing literature, highlights significance, discusses limitations, and suggests future research.}

# Conclusion
{Sometimes included at the end of the discussion to summarize key findings.}

# References
{A complete list of cited literature}